import type { PrimaryCollection } from "./contracts.ts";

export type RightsResearchStatus = "pending" | "researching" | "evidence-found" | "cleared" | "blocked";
export type CandidatePriority = "p0" | "p1" | "p2";

export interface CandidateRightsResearch {
  status: RightsResearchStatus;
  originalWorkNote: string;
  editionOrTranslationNote: string;
  evidenceReferences: string[];
  reviewedAt: string;
  reviewedBy: string;
}

export interface CatalogCandidate {
  slug: string;
  title: string;
  author: string;
  primaryCollections: PrimaryCollection[];
  topics: string[];
  priority: CandidatePriority;
  rationale: string;
  sourceLanguage: string;
  publicationState: "candidate";
  rightsResearch: CandidateRightsResearch;
}

const pendingRights = (originalWorkNote: string, editionOrTranslationNote = "Persian translation/edition rights must be researched independently before any publication decision."): CandidateRightsResearch => ({
  status: "pending",
  originalWorkNote,
  editionOrTranslationNote,
  evidenceReferences: [],
  reviewedAt: "",
  reviewedBy: "",
});

export const candidateRegistry: CatalogCandidate[] = [
  { slug: "meditations", title: "Meditations", author: "Marcus Aurelius", primaryCollections: ["philosophy-thinking", "personal-growth-habits"], topics: ["stoicism", "resilience", "self-discipline"], priority: "p0", rationale: "Evergreen practical philosophy with strong fit for short-form learning.", sourceLanguage: "grc", publicationState: "candidate", rightsResearch: pendingRights("Ancient original work; exact source edition still requires verification.") },
  { slug: "the-republic", title: "The Republic", author: "Plato", primaryCollections: ["philosophy-thinking", "history-society"], topics: ["justice", "politics", "ethics"], priority: "p1", rationale: "Foundational ideas with durable educational demand.", sourceLanguage: "grc", publicationState: "candidate", rightsResearch: pendingRights("Ancient original work; exact source edition still requires verification.") },
  { slug: "nicomachean-ethics", title: "Nicomachean Ethics", author: "Aristotle", primaryCollections: ["philosophy-thinking", "personal-growth-habits"], topics: ["ethics", "virtue", "decision-making"], priority: "p1", rationale: "Strong thematic fit for character, judgment and habits.", sourceLanguage: "grc", publicationState: "candidate", rightsResearch: pendingRights("Ancient original work; exact source edition still requires verification.") },
  { slug: "the-art-of-war", title: "The Art of War", author: "Sun Tzu", primaryCollections: ["management-leadership", "history-society"], topics: ["strategy", "leadership", "competition"], priority: "p0", rationale: "Compact strategy classic with strong management relevance.", sourceLanguage: "zh", publicationState: "candidate", rightsResearch: pendingRights("Ancient original work; exact source edition still requires verification.") },
  { slug: "tao-te-ching", title: "Tao Te Ching", author: "Laozi", primaryCollections: ["philosophy-thinking", "personal-growth-habits"], topics: ["taoism", "simplicity", "leadership"], priority: "p1", rationale: "Short-form philosophical work suited to reflective audio treatment.", sourceLanguage: "zh", publicationState: "candidate", rightsResearch: pendingRights("Ancient original work; exact source edition still requires verification.") },
  { slug: "the-prince", title: "The Prince", author: "Niccolò Machiavelli", primaryCollections: ["management-leadership", "history-society"], topics: ["power", "leadership", "political-strategy"], priority: "p0", rationale: "Recognizable strategy text with leadership and history crossover.", sourceLanguage: "it", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "essays-bacon", title: "Essays", author: "Francis Bacon", primaryCollections: ["philosophy-thinking", "personal-growth-habits"], topics: ["judgment", "learning", "conduct"], priority: "p2", rationale: "Modular essay structure supports concise editorial packaging.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "wealth-of-nations", title: "The Wealth of Nations", author: "Adam Smith", primaryCollections: ["economics-investing", "history-society"], topics: ["economics", "markets", "division-of-labor"], priority: "p0", rationale: "Foundational economics title with strong category value.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "on-liberty", title: "On Liberty", author: "John Stuart Mill", primaryCollections: ["philosophy-thinking", "history-society"], topics: ["liberty", "society", "individual-rights"], priority: "p1", rationale: "High-value civic and philosophical reading with modern relevance.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "utilitarianism", title: "Utilitarianism", author: "John Stuart Mill", primaryCollections: ["philosophy-thinking"], topics: ["ethics", "utility", "moral-reasoning"], priority: "p2", rationale: "Compact ethical framework suitable for structured explanation.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "self-reliance", title: "Self-Reliance", author: "Ralph Waldo Emerson", primaryCollections: ["personal-growth-habits", "philosophy-thinking"], topics: ["independence", "confidence", "individualism"], priority: "p1", rationale: "Short classic essay aligned with self-development demand.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "walden", title: "Walden", author: "Henry David Thoreau", primaryCollections: ["personal-growth-habits", "philosophy-thinking"], topics: ["simplicity", "nature", "intentional-living"], priority: "p1", rationale: "Recognizable classic with lifestyle and philosophy crossover.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "autobiography-benjamin-franklin", title: "The Autobiography of Benjamin Franklin", author: "Benjamin Franklin", primaryCollections: ["biography", "personal-growth-habits"], topics: ["biography", "habits", "self-improvement"], priority: "p0", rationale: "Biography plus habit-building makes it unusually aligned with Zobdino.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "narrative-frederick-douglass", title: "Narrative of the Life of Frederick Douglass", author: "Frederick Douglass", primaryCollections: ["biography", "history-society"], topics: ["biography", "history", "freedom"], priority: "p1", rationale: "Important first-person historical work with educational value.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "democracy-in-america", title: "Democracy in America", author: "Alexis de Tocqueville", primaryCollections: ["history-society", "philosophy-thinking"], topics: ["democracy", "institutions", "society"], priority: "p2", rationale: "Foundational political sociology with durable reference value.", sourceLanguage: "fr", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "communist-manifesto", title: "The Communist Manifesto", author: "Karl Marx and Friedrich Engels", primaryCollections: ["history-society", "economics-investing"], topics: ["political-economy", "history", "class"], priority: "p2", rationale: "Historically influential text useful for balanced educational coverage.", sourceLanguage: "de", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "federalist-papers", title: "The Federalist Papers", author: "Alexander Hamilton, James Madison and John Jay", primaryCollections: ["history-society", "philosophy-thinking"], topics: ["government", "institutions", "constitutional-design"], priority: "p2", rationale: "Primary-source political thought suitable for curated learning paths.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "origin-of-species", title: "On the Origin of Species", author: "Charles Darwin", primaryCollections: ["science-future", "history-society"], topics: ["evolution", "biology", "science-history"], priority: "p0", rationale: "Flagship science classic that expands category breadth.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "descent-of-man", title: "The Descent of Man", author: "Charles Darwin", primaryCollections: ["science-future", "history-society"], topics: ["evolution", "human-origins", "science-history"], priority: "p2", rationale: "Companion science-history candidate for deeper catalog coverage.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "interpretation-of-dreams", title: "The Interpretation of Dreams", author: "Sigmund Freud", primaryCollections: ["psychology-communication", "history-society"], topics: ["psychology", "dreams", "psychoanalysis"], priority: "p1", rationale: "Highly recognizable psychology classic with strong discovery demand.", sourceLanguage: "de", publicationState: "candidate", rightsResearch: pendingRights("Original-work and source-edition status varies by jurisdiction; verify before use.") },
  { slug: "psychopathology-of-everyday-life", title: "The Psychopathology of Everyday Life", author: "Sigmund Freud", primaryCollections: ["psychology-communication"], topics: ["psychology", "memory", "behavior"], priority: "p2", rationale: "Shorter psychology classic useful for testing category interest.", sourceLanguage: "de", publicationState: "candidate", rightsResearch: pendingRights("Original-work and source-edition status varies by jurisdiction; verify before use.") },
  { slug: "how-to-live-on-24-hours-a-day", title: "How to Live on 24 Hours a Day", author: "Arnold Bennett", primaryCollections: ["personal-growth-habits"], topics: ["time-management", "habits", "productivity"], priority: "p0", rationale: "Compact productivity classic suited to the under-20-minute shelf.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "science-of-getting-rich", title: "The Science of Getting Rich", author: "Wallace D. Wattles", primaryCollections: ["business-entrepreneurship", "personal-growth-habits"], topics: ["wealth", "mindset", "self-development"], priority: "p1", rationale: "Commercially recognizable historical self-development candidate.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "as-a-man-thinketh", title: "As a Man Thinketh", author: "James Allen", primaryCollections: ["personal-growth-habits", "philosophy-thinking"], topics: ["mindset", "thought", "character"], priority: "p0", rationale: "Very concise classic with strong audio-summary fit.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
  { slug: "souls-of-black-folk", title: "The Souls of Black Folk", author: "W. E. B. Du Bois", primaryCollections: ["history-society", "biography"], topics: ["history", "society", "identity"], priority: "p2", rationale: "Important social-history work that improves catalog breadth.", sourceLanguage: "en", publicationState: "candidate", rightsResearch: pendingRights("Historical original work; source edition and translation rights need verification.") },
];
