import type { CatalogEntry } from "./contracts.ts";

export const catalogRegistry: CatalogEntry[] = [
  {
    slug: "atomic-habits",
    titleFa: "عادت‌های اتمی",
    titleEn: "Atomic Habits",
    authorFa: "جیمز کلیر",
    authorEn: "James Clear",
    publicationYear: 2018,
    primaryCollections: ["personal-growth-habits"],
    topics: ["habits", "behavior-change", "personal-growth"],
    audienceLevel: "introductory",
    listeningMinutes: 14,
    publicationEra: "2010s",
    authorRegion: "US",
    format: "summary",
    voices: ["sulafat", "iapetus"],
    sourceLanguage: "en",
    editorialStatus: "candidate",
    rights: {
      status: "unknown",
      provenance: {
        type: "unknown",
        reference: "legacy-catalog-entry; rights evidence not yet migrated",
        verifiedAt: "",
        verifiedBy: "",
      },
    },
    publicationState: "legacy-unverified",
    shelves: ["quick-start", "under-20-min"],
  },
  {
    slug: "deep-work",
    titleFa: "کار عمیق",
    titleEn: "Deep Work",
    authorFa: "کال نیوپورت",
    authorEn: "Cal Newport",
    publicationYear: 2016,
    primaryCollections: ["personal-growth-habits", "management-leadership"],
    topics: ["focus", "productivity", "knowledge-work"],
    audienceLevel: "intermediate",
    listeningMinutes: 12,
    publicationEra: "2010s",
    authorRegion: "US",
    format: "summary",
    voices: ["sulafat", "iapetus"],
    sourceLanguage: "en",
    editorialStatus: "candidate",
    rights: {
      status: "unknown",
      provenance: {
        type: "unknown",
        reference: "legacy-catalog-entry; rights evidence not yet migrated",
        verifiedAt: "",
        verifiedBy: "",
      },
    },
    publicationState: "legacy-unverified",
    shelves: ["for-managers", "under-20-min"],
  },
];
